name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Our tests may contain a number of stochastic elements. Setting a seed will make sure they are
  # not flaky (but also hide potential issues).
  SEED: "0"

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: test_requirements.txt
      - name: Install dependencies
        run: pip install --no-dependencies -r test_requirements.txt
      - name: Run the tests
        run: doit tests
      - name: Lint the code
        run: doit lint
      - name: Build the documentation
        run: doit docs
